# Site settings
title:          Stefano Dalla Bona
description:    Personal Webpage
url:           https://stefanodallabona.github.io

# Author
author:      Stefano Dalla Bona
  name:        Stefano
  email:        stefanodallabona97@gmail.com
  url:           https://stefanodallabona.github.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: stefanodallabona97@gmail.com
  twitter: 
  linkedIn: 
  github: https://github.com/StefanoDallaBona
