# Site settings
title:          Le mie attività
description:    "Personal Webpage"
url:            https://github.com/inelaah/rain

# Author
author:
  name:         Stefano Dalla Bona
  email:        stefano.dallabona@phd.unipd.it
  url:         

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: stefanodallabona97@gmail.com
  github: https://github.com/StefanoDallaBona
  twitter: 
  linkedin: 
